version: '3.1'

services:
  genealogy-portal:
    image: genealogy-portal
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:mariadb://mariadb:3306/genealogy?createDatabaseIfNotExist=true
      DB_USERNAME: root
      DB_PASSWORD: root
      REDIS_HOST: redis
      REDIS_PORT: 6379
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
#    volumes:
#      - ../docker-volume/mariadb:/var/lib/mysql:Z
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
#    volumes:
#        - ../docker-volume/redis:/data