spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/genealogy?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      port: 6379
      host: localhost